$path = 'dermaplaning.html'
$content = Get-Content -Raw $path

$content = $content.Replace('id="section-benefits" class="treatment-section" style="background: var(--neutral-surface);"', 'id="section-benefits" class="treatment-section dermaplaning-benefits-section" style="background: var(--neutral-surface);"')
$content = $content.Replace('<p>Discover what makes dermaplaning special</p>', '<p>Discover what makes dermaplaning special with visible improvements from your very first session.</p>')
$content = $content.Replace('<div class="benefits-results-wrap">', '<div class="benefits-results-wrap dermaplaning-benefits-layout">')
$content = $content.Replace('<i class="fas fa-makeup"></i>', '<i class="fas fa-brush"></i>')
$content = $content.Replace('<h4>Improved Skincare Absorption</h4>', '<h4>Improved Product Absorption</h4>')
$content = $content.Replace('<p>Reveals fresher, radiant skin underneath dull surface layers</p>', '<p>Reveals fresher, radiant skin beneath dull surface buildup.</p>')
$content = $content.Replace('<p>Removes dead skin cells and peach fuzz for a polished finish</p>', '<p>Removes dead skin cells and peach fuzz for a polished finish.</p>')
$content = $content.Replace('<p>Maximises benefits of serums and moisturisers</p>', '<p>Helps serums and moisturisers penetrate more effectively.</p>')
$content = $content.Replace('<p>Creates smooth canvas for makeup application</p>', '<p>Creates a smoother canvas for seamless, even makeup wear.</p>')
$content = $content.Replace('<h4>Gentle & Non-Invasive</h4>', '<h4>Gentle and Non-Invasive</h4>')
$content = $content.Replace('<p>Safe for all skin types with minimal downtime</p>', '<p>Suitable for most skin types with minimal to no downtime.</p>')
$content = $content.Replace('<h4>Refines Texture & Softens Fine Lines</h4>', '<h4>Refined Texture</h4>')
$content = $content.Replace('<p>Encourages cellular renewal for youthful-looking skin</p>', '<p>Softens roughness and supports a fresher, more youthful look.</p>')

$oldResults = '<div class="results-panel" style="margin-top: 20px;">                      <div class="results-card">                          <div class="results-media">                              <img src="images/HydraFacial_Before_and_After.webp" alt="Dermaplaning before and after results" loading="lazy" style="width: 100%; height: 100%; object-fit: cover; border: 6px solid #D79582; border-radius: 12px; display: block;">                          </div>                          <div class="results-body">                          </div>                      </div>                  </div>'
$newResults = '<div class="results-panel">                      <div class="results-card dermaplaning-results-card">                          <div class="results-media dermaplaning-results-media">                              <img src="images/HydraFacial_Before_and_After.webp" alt="Dermaplaning before and after results" loading="lazy">                          </div>                          <div class="results-body dermaplaning-results-body">                              <h3>Real, Noticeable Results</h3>                              <p>Clients typically notice smoother texture, brighter tone, and better makeup finish straight after treatment.</p>                              <ul class="results-list">                                  <li><i class="fas fa-circle-check"></i> Immediate glow and softness</li>                                  <li><i class="fas fa-circle-check"></i> Cleaner, more even skin surface</li>                                  <li><i class="fas fa-circle-check"></i> Enhanced skincare performance</li>                              </ul>                          </div>                      </div>                  </div>'
$content = $content.Replace($oldResults, $newResults)

$insertCss = '<style>          .dermaplaning-benefits-layout {              grid-template-columns: minmax(0, 1.2fr) minmax(320px, 0.9fr);              gap: 28px;              align-items: stretch;          }            .dermaplaning-benefits-section .benefits-panel,          .dermaplaning-benefits-section .results-panel,          .dermaplaning-benefits-section .results-card {              height: 100%;          }            .dermaplaning-benefits-section .benefit-card {              min-height: 200px;              justify-content: flex-start;          }            .dermaplaning-results-card {              background: linear-gradient(135deg, var(--bg-white) 0%, var(--neutral-surface) 100%);              border: 1px solid rgba(158, 42, 54, 0.18);              border-radius: 12px;              box-shadow: 0 10px 24px rgba(158, 42, 54, 0.12);              overflow: hidden;          }            .dermaplaning-results-media {              width: 100%;              min-height: 0;              margin-top: 0;              aspect-ratio: 16 / 10;          }            .dermaplaning-results-media img {              width: 100%;              height: 100%;              object-fit: cover;              display: block;              border: 0;              border-radius: 0;          }            .dermaplaning-results-body {              padding: 18px;              gap: 12px;          }            .dermaplaning-results-body h3 {              font-size: 1.2rem;          }            .dermaplaning-results-body .results-list li {              align-items: flex-start;              font-size: 0.95rem;              line-height: 1.5;          }            @media (max-width: 1024px) {              .dermaplaning-benefits-layout {                  grid-template-columns: 1fr;              }          }            @media (max-width: 640px) {              .dermaplaning-results-body {                  padding: 16px;              }          }            .experience-grid {'
$content = $content.Replace('<style>          .experience-grid {', $insertCss)

Set-Content -Path $path -Value $content -NoNewline
Write-Output 'Done'
